export const Users = [
  {
    id:1,
    profilePicture: "person/1.jpeg",
    username: "Safak Kocaoglu",
  },
  {
    id:2,
    profilePicture: "person/2.jpeg",
    username: "Janell Shrum",
  },
  {
    id:3,
    profilePicture: "person/3.jpeg",
    username: "Alex Durden",
  },
  {
    id:4,
    profilePicture: "person/4.jpeg",
    username: "Dora Hawks",
  },
  {
    id:5,
    profilePicture: "person/5.jpeg",
    username: "Thomas Holden",
  },
  {
    id:6,
    profilePicture: "person/6.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "person/7.jpeg",
    username: "Travis Bennett",
  },
  {
    id:8,
    profilePicture: "person/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "person/9.jpeg",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "person/10.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const PostData = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "https://th.bing.com/th/id/OIP.dPudFX9h8NmhPD1Gsq71agHaGE?pid=ImgDet&rs=1",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "https://th.bing.com/th/id/OIP.bqYCzww4nd6qu-N89ZGtnAHaHa?pid=ImgDet&rs=1",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "https://th.bing.com/th/id/OIP.dPudFX9h8NmhPD1Gsq71agHaGE?pid=ImgDet&rs=1",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "https://th.bing.com/th/id/OIP.bqYCzww4nd6qu-N89ZGtnAHaHa?pid=ImgDet&rs=1",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "https://th.bing.com/th/id/OIP.fSxvQ4-18X7R212uxaDKcQHaE8?pid=ImgDet&rs=1",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "https://i.pinimg.com/originals/e0/4a/af/e04aaf667d86c663dede9ccff22821ef.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "https://th.bing.com/th/id/OIP.fSxvQ4-18X7R212uxaDKcQHaE8?pid=ImgDet&rs=1",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "https://wishyourfrnds.com/wp-content/uploads/2021/02/inspirational-quotes-by-famous-people-10.png",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "https://th.bing.com/th/id/R.3d733ee4cfcb1e7c4b54c61549c7d226?rik=tbrcvbYhknBViw&riu=http%3a%2f%2femilysquotes.com%2fwp-content%2fuploads%2f2014%2f01%2fEmilysQuotes.Com-dreams-true-courage-inspirational-positive-attitude-Walt-Disney-amazing.jpg&ehk=Iw%2bbfPx5JTRs9y0J05XU0nr9%2bDxzQ7kfdMJ11Yx%2fMTE%3d&risl=&pid=ImgRaw&r=0",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "https://th.bing.com/th/id/OIP.7g5fhgLySyKnocigNlriOgHaKl?pid=ImgDet&rs=1",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];